name: Buildx release
on:
  release:
    types: [published]
    paths-ignore:
      - .github/workflows/build.yml
      - .github/workflows/buildx-latest.yml
      - .github/workflows/dockerhub-description.yml
      - .dockerignore
      - .gitignore
      - docker-compose.yml
      - LICENSE
      - readme.md
      - title.png
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildx setup
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Dockerhub login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u qmcgaw --password-stdin 2>&1
      - name: Run Buildx
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6 \
            --build-arg CREATED=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg COMMIT=`git rev-parse --short HEAD` \
            --build-arg VERSION=${GITHUB_REF##*/} \
            -t qmcgaw/stackedit:${GITHUB_REF##*/} \
            --push \
            .
