name: Docker build
on:
  pull_request:
    branches: [master]
    paths-ignore:
      - .github/workflows/buildx-latest.yml
      - .github/workflows/buildx-release.yml
      - .github/workflows/dockerhub-description.yml
      - .dockerignore
      - .gitignore
      - docker-compose.yml
      - LICENSE
      - readme.md
      - title.png
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build .
